[system]
# 主程序端口
addr = "0.0.0.0:5000"
# 模式 debug/release
mode = "debug"
# 网站URL
website_url = "http://w4w.cc"
[db]
# 数据库
dialect = "mysql"
# 数据库连接字符串
address = "root:123456@tcp(127.0.0.1:3306)/w4w?charset=utf8&parseTime=True"
# 是否开启数据库日志
log = true
# 最大连接
max_open = 100
# 最大闲置
max_idle = 10